# Generated by Django 5.2.2 on 2025-12-10 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='psychologist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'psychologist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Психолог'),
        ),
    ]
